[package]
name = "compile-steno"
version = "0.1.0"
authors = ["crides <zhuhaoqing@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
serde_json = "*"
parse_int = "*"
primes = "*"
lazy_static = "*"
