[package]
name = "steno"
version = "0.1.0"
authors = ["crides <zhuhaoqing@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
clap = "2.33.1"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.55"
parse_int = "0.4.0"
primes = "0.3.0"
lazy_static = "1.4.0"
bitfield = "0.13.2"
regex = "1.3.9"
hidapi-sys = { path = "lib/rust-hidapi-sys", features = ["build"] }
hid = { path = "lib/rust-hid" }
indicatif = "0.15.0"
chrono = "0.4.11"
lalrpop-util = "0.19.0"
